export const FETCH_STORY_IDS_REQUEST = "FETCH_STORY_IDS_REQUEST";
export const FETCH_STORY_IDS_SUCCESS = "FETCH_STORY_IDS_SUCCESS";

export const FETCH_STORIES_REQUEST = "FETCH_STORIES_REQUEST";
export const FETCH_STORIES_SUCCESS = "FETCH_STORIES_SUCCESS";